### PR TITLE
Filter puntuation & check against lowercase words

### PR DESCRIPTION
**Pull request by varadpoddar**
Use Regex to filter the punctuations and use toLower() function to match against lower case filter list.
Added few more words to the filter list.

### CODE REVIEW

**Comment by varadpoddar** [comment]
@itsmais I think this should work in a more robust manner. 
Other things to consider :
- Filter out numbers
- Add more words to the filter list

Also, Would you please label this pr for hacktoberfest if you do accept and merge it. :)

**Comment by itsmais** [comment]
@varadpoddar thank you!

**Comment by varadpoddar** [comment]
@itsmais I would like to work some more on this project,
Especially with the small issues, I listed above. Would you mind if I add more features? :)

**Comment by itsmais** [comment]
@varadpoddar Sure, but someone else worked on [increasing the child nodes in the the API response](https://github.com/itsmais/word-cloud-subreddit/issues/1). What are your other suggestions?

**Comment by varadpoddar** [comment]
A couple of things I noticed : 
- Numbers in the cloud
- Punctuations appended to words
- repeating words because of capitalizations

I worked on a solution that solves the above problems that I would like to submit for your consideration. :)

**Pull request merged**
